version: '2'
networks:
  etcd:
services:
  etcd-node1:
    image: quay.io/coreos/etcd
    container_name: etcd-node1
    command: etcd -name etcd-node1 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd-node1=http://etcd-node1:2380,etcd-node2=http://etcd-node2:2380,etcd-node3=http://etcd-node3:2380" -initial-cluster-state new
    ports:
      - "12379:2379"
      - 2380
    networks:
      - etcd
  etcd-node2:
    image: quay.io/coreos/etcd
    container_name: etcd-node2
    command: etcd -name etcd-node2 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd-node1=http://etcd-node1:2380,etcd-node2=http://etcd-node2:2380,etcd-node3=http://etcd-node3:2380" -initial-cluster-state new
    ports:
      - "22379:2379"
      - 2380
    networks:
      - etcd
  etcd-node3:
    image: quay.io/coreos/etcd
    container_name: etcd-node3
    command: etcd -name etcd-node3 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd-node1=http://etcd-node1:2380,etcd-node2=http://etcd-node2:2380,etcd-node3=http://etcd-node3:2380" -initial-cluster-state new
    ports:
      - "32379:2379"
      - 2380
    networks:
      - etcd
