# Use root/example as user/password credentials
version: '3.1'

secrets:
  mongo-root-passwd:
    file: mongo-root-passwd
  mongo-user-passwd:
    file: mongo-user-passwd

services:
  mongo:
    image: mongo:4.4.12
    container_name: mongo
    restart: always
    volumes:
      # 数据库文件挂载到主机上
      - ./data/db:/data/db
      # # mongo 运行后执行的任务
      # - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD_FILE: /var/run/secrets/mongo-root-passwd
      MONGO_INITDB_USERNAME: $MONGO_USER
      MONGO_INITDB_PASSWORD_FILE: /var/run/secrets/mongo-user-passwd
      MONGO_INITDB_DATABASE: $MONGO_DB

    ports:
      - 27017:27017
    secrets:
      - mongo-root-passwd
      - mongo-user-passwd

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: 3edc#EDC
      ME_CONFIG_MONGODB_URL: mongodb://root:3edc#EDC@mongo:27017/
