version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root #在此填写postgres的用户名
      POSTGRES_DB: postgres #在此填写postgres的数据库名，默认是postgres
      POSTGRES_PASSWORD: 3edc#EDC #在此填写posgres的数据库密码
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: 1358244533@qq.com #在此填写pgAdmin登录账户邮箱
      PGADMIN_DEFAULT_PASSWORD: 3edc#EDC #在此填写pgAdmin密码
    ports:
      - "8082:80"
