version: '3'
 
services:
  redis:
    container_name: 'redis'
    image: 'redis'
    restart: always
    ports:
      - 6379:6379
    command: redis-server --port 6379 --requirepass 3edc#EDC --appendonly yes
